name: MLops CI

on:
  push:
    branches:
      - main  # <--- CORREGIDO: "- main" en lugar de "-main"
  pull_request:
    branches:
      - main  # <--- CORREGIDO: "- main" en lugar de "-main"

jobs:
  workflow:
    runs-on: ubuntu-latest  # Corregido de "run-on" a "runs-on" (error común de escritura)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt




  
